export const AUTH_SERVICE = 'AUTH_SERVICE';
export const USERS_SERVICE = 'USERS_SERVICE';
export const PROFILES_SERVICE = 'PROFILES_SERVICE';
export const INTERACTIONS_SERVICE = 'INTERACTIONS_SERVICE';
export const MATCHES_SERVICE = 'MATCHES_SERVICE';
export const MESSAGES_SERVICE = 'MESSAGES_SERVICE';
export const SUBSCRIPTIONS_SERVICE = 'SUBSCRIPTIONS_SERVICE';
